### ISSUE TITLE
How important is the choice of prior

### ISSUE THREAD

**Issue by danlaw23** [AmherstCollege/STAT370-Spring16#17]
We read a little about Bayesian parameter estimation, and we learnt that the posterior dist is proportional to the prior x likelihood. We saw a little about how two different priors converged to similar posterior distributions in fig 8.9 (pg.287). I was wondering about how one would come up with sensible priors, and in which cases can a bad prior lead to a bad posterior distribution.

**Comment by nicholasjhorton** [comment]
This is really important (and one of the reason why Bayesian inference has been controversial at times).  Without intruding too far into @swang87 's territory I'd strongly encourage you to  carefully read (or reread) Rice's Example E on pages 94-96 of section 3.5.  I've created a simple Shiny app that demonstrates what happens when you change the prior (by specifying a difference alpha or beta parameter) or adding more data (by changing the y and n values).  You can find this at: 

https://r.amherst.edu/apps/nhorton/Shiny-Bayes/

I'll talk more about how one might think about optimistic and skeptical priors for sensitivity analyses but definitely agree that specifying a bad prior can lead to bad results.
