### ISSUE TITLE
Question about bootstrap

### ISSUE THREAD

**Issue by tlee18** [AmherstCollege/STAT370-Spring16#6]
For the bootstrap, I'm a little confused about sampling with or without replacement. Are we supposed to always sample with replacement for bootstrap? I remember learning about a randomization method that used sampling without replacement, but I'm not sure how that's related to bootstrapping.

**Comment by nicholasjhorton** [comment]
We always sample with replacement.  Otherwise we'd just end up with a permutation of the original data (and exactly the same statistics).  

A permutation test involves shuffling the group indicator for a two sample comparison (or similar problem).  That is where the sampling without replacement comes from.

The Wikipedia page on resampling provides a nice overview:
https://en.wikipedia.org/wiki/Resampling_%28statistics%29
